<a href="https://colab.research.google.com/github/2303A51090/b2_PDS_1090/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#Lab Question-01
import numpy as np

m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

m2 = np.array([[9, 8, 7],
               [6, 5, 4],
               [3, 2, 1]])

addition = np.add(m1, m2)
Subtraction = np.subtract(m1, m2)
print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)
print("Addition Result:\n", addition)
print("Subtraction Result:\n", Subtraction)


Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition Result:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction Result:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [9]:
#Lab Question -2
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

dot_product = np.dot(a, b)
print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Dot Product Result:\n", dot_product)


Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Dot Product Result:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [15]:
#files
file_name="student_data.txt"
name=input("Enter name: ")
marks=input("Enter marks: ")
with open(file_name,"a") as f:
    f.write(f"{name},{marks}\n")

print("\nAll Entries:")
with open(file_name,"r") as f:
    for line in f:
        n,m=line.strip().split(",")
        print(f"Name: {n}, Marks: {m}")

Enter name: anand
Enter marks: 90

All Entries:
Name: Anand, Marks: 90
Name: Anand, Marks: 90
Name: anand, Marks: 90
